apiVersion: v1
kind: ReplicationController
metadata:
  name: netchecker-agent
spec:
  replicas: 6
  selector:
    app: netchecker-agent
  template:
    metadata:
      name: netchecker-agent
      labels:
        app: netchecker-agent
    spec:
      containers:
        - name: netchecker-agent
          image: 127.0.0.1:31500/netchecker/agent:latest
          env:
          imagePullPolicy: Always

